// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OceanObservationAPI.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OpenSea.Migrations
{
    [DbContext(typeof(OceanDataContext))]
    [Migration("20240606010131_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OceanObservationAPI.Models.OceanObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Oxygen")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("PH")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Salinity")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Temperature")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("OceanObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
